# Configuração alternativa para Netlify (caso escolha usar)
[build]
  command = "npm run build"
  publish = "dist"
  
# Configurar redirecionamentos para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Configurar cabeçalhos para Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
    
# Configurar cabeçalhos para manifestação do PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"